from typing import Tuple, Optional, NoReturn


class SocketStreamServer:
    def __init__(self, server_address: str, client_address: Optional[str], windows_size: Tuple[int, int], /) -> NoReturn: ...

    def run(self) -> NoReturn: ...

class SocketStreamClient:
    def __init__(self, server_address: str, /) -> NoReturn: ...

    def run(self) -> NoReturn: ...
